# ubkg-guesdt docker compose
services:
  ubkg-guesdt:
    build:
      context:  ../
      dockerfile: ./docker/Dockerfile
      # Configure Compose for multi-architecture builds.
      # Prerequisites:
      # 1. Create an additional buildx builder by running
      #    docker buildx create --use
      # 2. Build tags for both the current version and "latest".
      tags:
        - docker.io/hubmap/ubkg-guesdt:latest
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    # Build the image with name and tag
    image: hubmap/ubkg-guesdt:latest