user nginx;
# Set the number of worker processes.
worker_processes 1;

pid /var/run/nginx.pid;
# Set number of worker connections.
events {
worker_connections 1024;
}
http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    access_log /usr/src/app/log/nginx_access_ubkg-guesdt.log;
    error_log /usr/src/app/log/nginx_error_ubkg-guesdt.log debug;
    # default logging format
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
    access_log  /var/log/nginx/access.log  main;
    server {
        listen 8080;
         # health status endpoint
         location = /status {
             access_log off;
             default_type text/plain;
             add_header Content-Type text/plain;
             return 200 "alive";
        }
        # Route all traffic to index.html.
         location / {
            gzip off;
            root /usr/share/nginx/html/guesdt/;
            index index.html;
            try_files $uri $uri/ =404;
        }
        # Serve requests for static resources such as JavaScript, Style sheets and images
        location ~* \.(js|jpg|png|css|pdf)$ {
            root /usr/share/nginx/html/guesdt/;
        }
    }
    # Optimize file sending.
    sendfile        on;
    keepalive_timeout  65;
}